// AUTO-GENERATED by macro-scraper.py — DO NOT EDIT
// Updated: 2026-02-25T08:50:02.679338+09:00

export interface MarketItem {
  price: number;
  change: number;
  changePercent: number;
}

export interface MacroData {
  updatedAt: string;
  market: {
    sp500: MarketItem;
    nasdaq: MarketItem;
    dow: MarketItem;
    vix: { value: number; changePercent: number };
    gold: MarketItem;
    oil: MarketItem;
    dollarIndex: MarketItem;
  };
  rates: {
    fed: number;
    treasury10y: number;
    treasury5y: number;
    treasury3m: number;
    yieldSpread10y3m: number;
    isInverted: boolean;
    sp500DivYield: number;
    bondStockSpread: number;
  };
  dividendScore: {
    score: number;
    label: string;
    rateSignal: string;
    marketSignal: string;
    valuationSignal: string;
  };
  dividends: {
    schd: MarketItem;
    nobl: MarketItem;
  };
  fed: {
    currentRate: number;
    nextFomcDate: string;
    daysUntilFomc: number;
  };
}

export const macroData: MacroData = {
  "updatedAt": "2026-02-25T08:50:02.679338+09:00",
  "market": {
    "sp500": {
      "price": 6890.07,
      "change": 52.32,
      "changePercent": 0.77
    },
    "nasdaq": {
      "price": 22863.68,
      "change": 236.41,
      "changePercent": 1.04
    },
    "dow": {
      "price": 49174.5,
      "change": 370.44,
      "changePercent": 0.76
    },
    "vix": {
      "value": 19.55,
      "changePercent": -6.95
    },
    "gold": {
      "price": 474.61,
      "change": -6.67,
      "changePercent": -1.39
    },
    "oil": {
      "price": 80.76,
      "change": -0.14,
      "changePercent": -0.17
    },
    "dollarIndex": {
      "price": 27.11,
      "change": 0.02,
      "changePercent": 0.07
    }
  },
  "rates": {
    "fed": 4.5,
    "treasury10y": 4.03,
    "treasury5y": 3.6,
    "treasury3m": 3.59,
    "yieldSpread10y3m": 0.44,
    "isInverted": false,
    "sp500DivYield": 1.36,
    "bondStockSpread": 2.67
  },
  "dividendScore": {
    "score": 5.0,
    "label": "중립",
    "rateSignal": "중립",
    "marketSignal": "중립",
    "valuationSignal": "채권 유리"
  },
  "dividends": {
    "schd": {
      "price": 31.64,
      "change": 0.11,
      "changePercent": 0.35
    },
    "nobl": {
      "price": 113.96,
      "change": 0.52,
      "changePercent": 0.46
    }
  },
  "fed": {
    "currentRate": 4.5,
    "nextFomcDate": "2026-03-19",
    "daysUntilFomc": 22
  }
};
