// AUTO-GENERATED by macro-scraper.py — DO NOT EDIT
// Updated: 2026-02-26T08:50:02.041845+09:00

export interface MarketItem {
  price: number;
  change: number;
  changePercent: number;
}

export interface MacroData {
  updatedAt: string;
  market: {
    sp500: MarketItem;
    nasdaq: MarketItem;
    dow: MarketItem;
    vix: { value: number; changePercent: number };
    gold: MarketItem;
    oil: MarketItem;
    dollarIndex: MarketItem;
  };
  rates: {
    fed: number;
    treasury10y: number;
    treasury5y: number;
    treasury3m: number;
    yieldSpread10y3m: number;
    isInverted: boolean;
    sp500DivYield: number;
    bondStockSpread: number;
  };
  dividendScore: {
    score: number;
    label: string;
    rateSignal: string;
    marketSignal: string;
    valuationSignal: string;
  };
  dividends: {
    schd: MarketItem;
    nobl: MarketItem;
  };
  fed: {
    currentRate: number;
    nextFomcDate: string;
    daysUntilFomc: number;
  };
}

export const macroData: MacroData = {
  "updatedAt": "2026-02-26T08:50:02.041845+09:00",
  "market": {
    "sp500": {
      "price": 6946.13,
      "change": 56.06,
      "changePercent": 0.81
    },
    "nasdaq": {
      "price": 23152.08,
      "change": 288.4,
      "changePercent": 1.26
    },
    "dow": {
      "price": 49482.15,
      "change": 307.65,
      "changePercent": 0.63
    },
    "vix": {
      "value": 17.93,
      "changePercent": -8.29
    },
    "gold": {
      "price": 473.42,
      "change": -1.19,
      "changePercent": -0.25
    },
    "oil": {
      "price": 79.73,
      "change": -1.03,
      "changePercent": -1.28
    },
    "dollarIndex": {
      "price": 27.08,
      "change": -0.03,
      "changePercent": -0.11
    }
  },
  "rates": {
    "fed": 4.5,
    "treasury10y": 4.05,
    "treasury5y": 3.62,
    "treasury3m": 3.59,
    "yieldSpread10y3m": 0.46,
    "isInverted": false,
    "sp500DivYield": 1.36,
    "bondStockSpread": 2.69
  },
  "dividendScore": {
    "score": 5.5,
    "label": "중립",
    "rateSignal": "중립",
    "marketSignal": "안정",
    "valuationSignal": "채권 유리"
  },
  "dividends": {
    "schd": {
      "price": 31.51,
      "change": -0.13,
      "changePercent": -0.41
    },
    "nobl": {
      "price": 113.33,
      "change": -0.63,
      "changePercent": -0.55
    }
  },
  "fed": {
    "currentRate": 4.5,
    "nextFomcDate": "2026-03-19",
    "daysUntilFomc": 21
  }
};
