// AUTO-GENERATED by macro-scraper.py — DO NOT EDIT
// Updated: 2026-02-22T09:55:07.250112+09:00

export interface MarketItem {
  price: number;
  change: number;
  changePercent: number;
}

export interface MacroData {
  updatedAt: string;
  market: {
    sp500: MarketItem;
    nasdaq: MarketItem;
    dow: MarketItem;
    vix: { value: number; changePercent: number };
    gold: MarketItem;
    oil: MarketItem;
    dollarIndex: MarketItem;
  };
  rates: {
    fed: number;
    treasury10y: number;
    treasury5y: number;
    treasury3m: number;
    yieldSpread10y3m: number;
    isInverted: boolean;
    sp500DivYield: number;
    bondStockSpread: number;
  };
  dividendScore: {
    score: number;
    label: string;
    rateSignal: string;
    marketSignal: string;
    valuationSignal: string;
  };
  dividends: {
    schd: MarketItem;
    nobl: MarketItem;
  };
  fed: {
    currentRate: number;
    nextFomcDate: string;
    daysUntilFomc: number;
  };
}

export const macroData: MacroData = {
  "updatedAt": "2026-02-22T09:55:07.250112+09:00",
  "market": {
    "sp500": {
      "price": 6909.51,
      "change": 47.62,
      "changePercent": 0.69
    },
    "nasdaq": {
      "price": 22886.07,
      "change": 203.34,
      "changePercent": 0.9
    },
    "dow": {
      "price": 49625.97,
      "change": 230.81,
      "changePercent": 0.47
    },
    "vix": {
      "value": 19.09,
      "changePercent": -5.64
    },
    "gold": {
      "price": 468.62,
      "change": 9.06,
      "changePercent": 1.97
    },
    "oil": {
      "price": 80.85,
      "change": -0.34,
      "changePercent": -0.42
    },
    "dollarIndex": {
      "price": 27.09,
      "change": -0.03,
      "changePercent": -0.11
    }
  },
  "rates": {
    "fed": 4.5,
    "treasury10y": 4.09,
    "treasury5y": 3.65,
    "treasury3m": 3.6,
    "yieldSpread10y3m": 0.49,
    "isInverted": false,
    "sp500DivYield": 1.36,
    "bondStockSpread": 2.73
  },
  "dividendScore": {
    "score": 5.0,
    "label": "중립",
    "rateSignal": "중립",
    "marketSignal": "중립",
    "valuationSignal": "채권 유리"
  },
  "dividends": {
    "schd": {
      "price": 31.61,
      "change": 0.04,
      "changePercent": 0.13
    },
    "nobl": {
      "price": 113.67,
      "change": 0.49,
      "changePercent": 0.43
    }
  },
  "fed": {
    "currentRate": 4.5,
    "nextFomcDate": "2026-03-19",
    "daysUntilFomc": 25
  }
};
